import { compactSearchText } from "./exerciseSearch";

const baseExerciseNames = [
  "Ab wheel rollout",
  "Arnold press",
  "Back extension",
  "Back squat",
  "Barbell bench press",
  "Barbell curl",
  "Barbell hip thrust",
  "Barbell row",
  "Battle ropes",
  "Behind-the-neck press",
  "Belt squat",
  "Bent-over row",
  "Bicycle crunch",
  "Box jump",
  "Box squat",
  "Bulgarian split squat",
  "Burpee",
  "Cable chest fly",
  "Cable crunch",
  "Cable curl",
  "Cable lateral raise",
  "Cable overhead triceps extension",
  "Cable pull-through",
  "Cable row",
  "Cable woodchop",
  "Calf press",
  "Chest dip",
  "Chest press machine",
  "Chest-supported row",
  "Chin-up",
  "Clean",
  "Clean and jerk",
  "Close-grip bench press",
  "Concentration curl",
  "Conventional deadlift",
  "Crunch",
  "Cycling",
  "Dead bug",
  "Decline bench press",
  "Deficit deadlift",
  "Dip",
  "Donkey calf raise",
  "Dumbbell bench press",
  "Dumbbell curl",
  "Dumbbell fly",
  "Dumbbell front raise",
  "Dumbbell lateral raise",
  "Dumbbell lunge",
  "Dumbbell pullover",
  "Dumbbell row",
  "Dumbbell shoulder press",
  "Elliptical",
  "Face pull",
  "Farmer’s carry",
  "Flat bench press",
  "Front squat",
  "Glute bridge",
  "Goblet squat",
  "Good morning",
  "Hack squat",
  "Hammer curl",
  "Handstand push-up",
  "Hanging knee raise",
  "Hanging leg raise",
  "High pull",
  "Hip abduction machine",
  "Hip adduction machine",
  "Incline barbell bench press",
  "Incline dumbbell bench press",
  "Incline dumbbell curl",
  "Inverted row",
  "Jefferson curl",
  "Jump rope",
  "Kettlebell clean",
  "Kettlebell swing",
  "Lat pulldown",
  "Lateral lunge",
  "Leg extension",
  "Leg press",
  "Lying leg curl",
  "Machine chest fly",
  "Machine lateral raise",
  "Machine shoulder press",
  "Meadows row",
  "Military press",
  "Nordic hamstring curl",
  "Overhead press",
  "Overhead squat",
  "Pec deck",
  "Pendlay row",
  "Pistol squat",
  "Plank",
  "Power clean",
  "Preacher curl",
  "Pull-up",
  "Push press",
  "Push-up",
  "Rack pull",
  "Rear delt fly",
  "Reverse curl",
  "Reverse fly machine",
  "Reverse lunge",
  "Romanian deadlift",
  "Rope pushdown",
  "Rowing machine",
  "Running",
  "Russian twist",
  "Seated cable row",
  "Seated calf raise",
  "Seated leg curl",
  "Shrug",
  "Side plank",
  "Single-arm cable row",
  "Single-leg Romanian deadlift",
  "Sissy squat",
  "Skull crusher",
  "Sled drag",
  "Sled push",
  "Smith machine bench press",
  "Smith machine squat",
  "Snatch",
  "Spider curl",
  "Split squat",
  "Standing calf raise",
  "Step-up",
  "Straight-arm pulldown",
  "Sumo deadlift",
  "T-bar row",
  "Thruster",
  "Toe touch",
  "Trap-bar deadlift",
  "Triceps dip",
  "Triceps pushdown",
  "Upright row",
  "Walking",
  "Walking lunge",
  "Wall sit",
  "Wide-grip pulldown",
  "Wrist curl",
  "Zercher squat",
  "Zottman curl",
  "1-arm dumbbell recline curl",
  "Bayesian cable curl",
  "Cable cuff lateral raise",
  "Cable cuff Y-raise",
  "Cable lat prayer",
  "Cable lat pullover",
  "Cable preacher curl",
  "Cable reverse fly",
  "Cable wrist cuff lateral raise",
  "Cross-body cable lat pull-around",
  "Cross-body cable triceps extension",
  "Cuffed cable pulldown",
  "Cuffed rear delt fly",
  "Deep stretch push-up",
  "Deficit push-up",
  "Dual-cable chest press",
  "EZ-bar Bayesian curl",
  "Frontal-plane Keenan flap",
  "Iliac lat pulldown",
  "Incline cable chest press",
  "Incline cable curl",
  "Incline cable fly",
  "JM press",
  "Katana triceps extension",
  "Keenan flap",
  "Kelso shrug",
  "Kneeling lat pulldown",
  "Larsen press",
  "Lengthened-partial cable lateral raise",
  "Lengthened-partial leg extension",
  "Lengthened-partial pull-up",
  "Lengthened-partial preacher curl",
  "Long-length partial calf raise",
  "Long-length partial leg curl",
  "Lu raise",
  "Machine preacher curl",
  "Machine pullover",
  "Omni-directional lateral raise",
  "Overhead cable curl",
  "Pendulum squat",
  "Recline curl",
  "Reverse Nordic curl",
  "Sagittal-plane Keenan flap",
  "Seated cable fly",
  "Seated good morning",
  "Single-arm cable pulldown",
  "Single-arm lat prayer",
  "Smith machine JM press",
  "Smith machine lunge",
  "Smith machine Romanian deadlift",
  "Stretch-mediated calf raise",
  "Supported recline curl",
  "Upper-back-biased cable row",
  "Upper-back-biased chest-supported row",
  "Alternating dumbbell bench press",
  "Alternating dumbbell curl",
  "Alternating dumbbell shoulder press",
  "Arnold dumbbell press",
  "Dumbbell chest-supported row",
  "Dumbbell clean",
  "Dumbbell deadlift",
  "Dumbbell decline bench press",
  "Dumbbell floor press",
  "Dumbbell front squat",
  "Dumbbell hammer curl",
  "Dumbbell incline fly",
  "Dumbbell incline row",
  "Dumbbell incline shoulder press",
  "Dumbbell overhead triceps extension",
  "Dumbbell rear delt row",
  "Dumbbell Romanian deadlift",
  "Dumbbell reverse fly",
  "Dumbbell reverse lunge",
  "Dumbbell seal row",
  "Dumbbell snatch",
  "Dumbbell split squat",
  "Dumbbell step-up",
  "Dumbbell sumo squat",
  "Dumbbell sumo deadlift",
  "Dumbbell swing",
  "Dumbbell thruster",
  "Dumbbell upright row",
  "Dumbbell walking lunge",
  "Dumbbell Y-raise",
  "Dumbbell Zottman curl",
  "Farmer carry",
  "Front rack dumbbell carry",
  "Renegade row",
  "Single-arm dumbbell bench press",
  "Single-arm dumbbell floor press",
  "Single-arm dumbbell row",
  "Single-arm dumbbell shoulder press",
  "Suitcase carry",
  "Waiter carry",
  "Barbell clean",
  "Barbell clean and press",
  "Barbell complex",
  "Barbell deadlift",
  "Barbell decline bench press",
  "Barbell floor press",
  "Barbell front squat",
  "Barbell hack squat",
  "Barbell overhead press",
  "Barbell reverse lunge",
  "Barbell seal row",
  "Barbell shrug",
  "Barbell snatch",
  "Barbell split squat",
  "Barbell step-up",
  "Barbell sumo deadlift",
  "Barbell thruster",
  "Barbell upright row",
  "Barbell walking lunge",
  "Barbell wrist curl",
  "Block pull",
  "Deficit barbell row",
  "Landmine press",
  "Landmine row",
  "Landmine squat",
  "Meadows press",
  "Pendlay deadlift",
  "Pin press",
  "Pause bench press",
  "Pause squat",
  "Paused deadlift",
  "Reverse-grip barbell bench press",
  "Safety bar squat",
  "Seal row",
  "Spoto press",
  "Stiff-leg deadlift",
  "Wide-grip barbell row",
  "Assisted dip machine",
  "Assisted pull-up machine",
  "Belt squat machine",
  "Cable crossover",
  "Chest press machine",
  "Chest-supported machine row",
  "Glute drive machine",
  "Hack squat machine",
  "Hip thrust machine",
  "Horizontal leg press",
  "Incline chest press machine",
  "Lat pulldown machine",
  "Leg curl machine",
  "Leg press machine",
  "Pendulum squat machine",
  "Preacher curl machine",
  "Rear delt machine",
  "Seated dip machine",
  "Seated leg press",
  "Smith machine calf raise",
  "Smith machine deadlift",
  "Smith machine incline press",
  "Smith machine overhead press",
  "Smith machine reverse lunge",
  "Standing calf machine",
  "Standing leg curl machine",
  "Vertical leg press",
  "V-squat machine",
];

const communityExerciseNames = [
  "Assisted Dip",
  "Band-Assisted Bench Press",
  "Bar Dip",
  "Bench Press",
  "Bench Press Against Band",
  "Board Press",
  "Cable Chest Press",
  "Clap Push-Up",
  "Close-Grip Feet-Up Bench Press",
  "Cobra Push-Up",
  "Decline Push-Up",
  "Dumbbell Chest Fly",
  "Dumbbell Chest Press",
  "Dumbbell Decline Chest Press",
  "Feet-Up Bench Press",
  "Floor Press",
  "Incline Bench Press",
  "Incline Dumbbell Press",
  "Incline Push-Up",
  "Kettlebell Floor Press",
  "Kneeling Incline Push-Up",
  "Kneeling Push-Up",
  "Machine Chest Press",
  "Medicine Ball Chest Pass",
  "Plank to Push-Up",
  "Push-Up Against Wall",
  "Push-Ups With Feet in Rings",
  "Resistance Band Chest Fly",
  "Ring Dip",
  "Seated Cable Chest Fly",
  "Smith Machine Incline Bench Press",
  "Smith Machine Reverse Grip Bench Press",
  "Standing Cable Chest Fly",
  "Standing Resistance Band Chest Fly",
  "Arnold Press",
  "Band External Shoulder Rotation",
  "Band Internal Shoulder Rotation",
  "Band Pull-Apart",
  "Banded Face Pull",
  "Barbell Front Raise",
  "Barbell Rear Delt Row",
  "Behind the Neck Press",
  "Cable Internal Shoulder Rotation",
  "Cable External Shoulder Rotation",
  "Cable Front Raise",
  "Cable Rear Delt Row",
  "Cuban Press",
  "Devils Press",
  "Dumbbell Horizontal Internal Shoulder Rotation",
  "Dumbbell Horizontal External Shoulder Rotation",
  "Dumbbell Rear Delt Row",
  "Front Hold",
  "Jerk",
  "Kettlebell Halo",
  "Kettlebell Press",
  "Kettlebell Push Press",
  "Lying Dumbbell External Shoulder Rotation",
  "Lying Dumbbell Internal Shoulder Rotation",
  "Monkey Row",
  "One-Arm Landmine Press",
  "Overhead Press",
  "Plate Front Raise",
  "Poliquin Raise",
  "Power Jerk",
  "Resistance Band Lateral Raise",
  "Reverse Cable Flyes",
  "Reverse Dumbbell Flyes",
  "Reverse Dumbbell Flyes on Incline Bench",
  "Reverse Machine Fly",
  "Seated Dumbbell Shoulder Press",
  "Seated Barbell Overhead Press",
  "Seated Kettlebell Press",
  "Seated Smith Machine Shoulder Press",
  "Smith Machine Landmine Press",
  "Snatch Grip Behind the Neck Press",
  "Squat Jerk",
  "Split Jerk",
  "Turkish Get-Up",
  "Wall Walk",
  "Z Press",
  "Barbell Preacher Curl",
  "Bodyweight Curl",
  "Cable Crossover Bicep Curl",
  "Cable Curl With Bar",
  "Cable Curl With Rope",
  "Drag Curl",
  "Dumbbell Preacher Curl",
  "EZ Curl",
  "Kettlebell Curl",
  "Lying Bicep Cable Curl on Bench",
  "Lying Bicep Cable Curl on Floor",
  "Machine Bicep Curl",
  "Reverse Barbell Curl",
  "Reverse Dumbbell Curl",
  "Resistance Band Curl",
  "Barbell Standing Triceps Extension",
  "Barbell Incline Triceps Extension",
  "Barbell Lying Triceps Extension",
  "Bench Dip",
  "Crossbody Cable Triceps Extension",
  "Close-Grip Push-Up",
  "Dumbbell Lying Triceps Extension",
  "Dumbbell Standing Triceps Extension",
  "EZ Bar Lying Triceps Extension",
  "Machine Overhead Triceps Extension",
  "Overhead Cable Triceps Extension (Lower Position)",
  "Overhead Cable Triceps Extension (Upper Position)",
  "Smith Machine Skull Crushers",
  "Tate Press",
  "Tricep Bodyweight Extension",
  "Tricep Pushdown With Bar",
  "Tricep Pushdown With Rope",
  "Air Squat",
  "Banded Hip March",
  "Barbell Hack Squat",
  "Barbell Lunge",
  "Body Weight Lunge",
  "Bodyweight Leg Curl",
  "Chair Squat",
  "Curtsy Lunge",
  "Depth Jump",
  "Dumbbell Squat",
  "Glute Ham Raise",
  "Ground to Overhead",
  "Half Air Squat",
  "Heel Walk",
  "Hip Adduction Against Band",
  "Jump Squat",
  "Jumping Lunge",
  "Kettlebell Front Squat",
  "Kettlebell Thrusters",
  "Kettlebell Tibialis Raise",
  "Landmine Hack Squat",
  "Lateral Bound",
  "Leg Curl On Ball",
  "Nordic Hamstring Eccentric",
  "One-Legged Leg Extension",
  "One-Legged Lying Leg Curl",
  "One-Legged Seated Leg Curl",
  "One-Legged Leg Curl",
  "Pin Squat",
  "Poliquin Step-Up",
  "Prisoner Get Up",
  "Reverse Barbell Lunge",
  "Reverse Body Weight Lunge",
  "Reverse Dumbbell Lunge",
  "Reverse Nordic",
  "Safety Bar Squat",
  "Shallow Body Weight Lunge",
  "Side Lunges (Bodyweight)",
  "Smith Machine Bulgarian Split Squat",
  "Smith Machine Front Squat",
  "Standing Cable Leg Extension",
  "Standing Hip Flexor Raise",
  "Standing Leg Curl",
  "Step Up",
  "Tibialis Band Pull",
  "Tibialis Raise",
  "Zombie Squat",
  "Assisted Chin-Up",
  "Assisted Pull-Up",
  "Banded Muscle-Up",
  "Block Clean",
  "Block Snatch",
  "Cable Close Grip Seated Row",
  "Cable Wide Grip Seated Row",
  "Chest-Supported Dumbbell Row",
  "Chest to Bar",
  "Close-Grip Chin-Up",
  "Close-Grip Lat Pulldown",
  "Deadlift",
  "Dumbbell Shrug",
  "Floor Back Extension",
  "Gorilla Row",
  "Hang Clean",
  "Hang Power Clean",
  "Hang Power Snatch",
  "Hang Snatch",
  "Inverted Row with Underhand Grip",
  "Kettlebell Clean & Jerk",
  "Kettlebell Clean & Press",
  "Kettlebell Row",
  "Kettlebell Snatch",
  "Kroc Row",
  "Lat Pulldown With Neutral Grip",
  "Lat Pulldown With Pronated Grip",
  "Lat Pulldown With Supinated Grip",
  "Machine Lat Pulldown",
  "Muscle-Up (Bar)",
  "Muscle-Up (Rings)",
  "Neutral Close-Grip Lat Pulldown",
  "One-Handed Cable Row",
  "One-Handed Kettlebell Swing",
  "One-Handed Lat Pulldown",
  "Pause Deadlift",
  "Power Snatch",
  "Pull-Up With a Neutral Grip",
  "Ring Pull-Up",
  "Ring Row",
  "Scap Pull-Up",
  "Seated Machine Row",
  "Single Leg Deadlift with Kettlebell",
  "Smith Machine One-Handed Row",
  "Snatch Grip Deadlift",
  "Stiff-Legged Deadlift",
  "Straight Arm Lat Pulldown",
  "Superman Raise",
  "T-Bar Row",
  "Towel Row",
  "Trap Bar Deadlift With High Handles",
  "Trap Bar Deadlift With Low Handles",
  "Banded Side Kicks",
  "Cable Glute Kickback",
  "Cable Machine Hip Abduction",
  "Clamshells",
  "Cossack Squat",
  "Death March with Dumbbells",
  "Donkey Kicks",
  "Dumbbell Frog Pumps",
  "Fire Hydrants",
  "Frog Pumps",
  "Hip Thrust",
  "Hip Thrust With Band Around Knees",
  "Kettlebell Windmill",
  "Lateral Walk With Band",
  "Machine Glute Kickbacks",
  "One-Legged Glute Bridge",
  "One-Legged Hip Thrust",
  "Reverse Hyperextension",
  "Smith Machine Hip Thrust",
  "Standing Hip Abduction Against Band",
  "Standing Glute Kickback in Machine",
  "Standing Glute Push Down",
  "Ball Slams",
  "Captain's Chair Knee Raise",
  "Captain's Chair Leg Raise",
  "Copenhagen Plank",
  "Core Twist",
  "Dead Bug With Dumbbells",
  "Dragon Flag",
  "Dumbbell Side Bend",
  "Dynamic Side Plank",
  "Hanging Sit-Up",
  "Hanging Windshield Wiper",
  "High to Low Wood Chop with Band",
  "High to Low Wood Chop with Cable",
  "Hollow Body Crunch",
  "Hollow Hold",
  "Horizontal Wood Chop with Band",
  "Horizontal Wood Chop with Cable",
  "Jackknife Sit-Up",
  "Kettlebell Plank Pull Through",
  "Kneeling Ab Wheel Roll-Out",
  "Kneeling Plank",
  "Kneeling Side Plank",
  "Landmine Rotation",
  "L-Sit",
  "Low to High Wood Chop with Band",
  "Low to High Wood Chop with Cable",
  "Lying Leg Raise",
  "Lying Windshield Wiper",
  "Lying Windshield Wiper with Bent Knees",
  "Machine Crunch",
  "Mountain Climbers",
  "Oblique Crunch",
  "Oblique Sit-Up",
  "Pallof Press",
  "Plank with Leg Lifts",
  "Plank with Shoulder Taps",
  "Sit-Up",
  "Weighted Plank",
  "Barbell Standing Calf Raise",
  "Barbell Seated Calf Raise",
  "Calf Raise in Leg Press",
  "Eccentric Heel Drop",
  "Heel Raise",
  "Barbell Wrist Curl Behind the Back",
  "Bar Hang",
  "Dumbbell Wrist Curl",
  "Farmers Walk",
  "Fat Bar Deadlift",
  "Gripper",
  "One-Handed Bar Hang",
  "Plate Pinch",
  "Plate Wrist Curl",
  "Towel Pull-Up",
  "Wrist Roller",
  "Barbell Wrist Extension",
  "Dumbbell Wrist Extension",
  "Lying Neck Curl",
  "Lying Neck Extension",
  "Prone Neck Bridge",
  "Supine Neck Bridge",
  "Stationary Bike",
];

export const exerciseNames = [
  ...new Map([...baseExerciseNames, ...communityExerciseNames].map((name) => [compactSearchText(name), name])).values(),
].sort();
